### ISSUE TITLE
HAPQ Color banding (looks better in HAP)

### ISSUE THREAD

**Issue by tromerk** [Vidvox/hap-qt-codec#29] opened 2016-02-09 18:18 UTC
I am comparing (for now just 1 file) in many encoder and including HAP.  My final outputs are used in Dataton Watchout (http://www.dataton.com/watchout) which with version 6.x includes HAP support.

On this one file I am testing, I see some color variations and some noticeable banding with HAPQ that actually looks BETTER with HAP.
Here are some still frames from encode:
Original File:
https://dl.dropboxusercontent.com/u/20646203/Original%20%28QT%20Animation%29.png 

HAP:
https://dl.dropboxusercontent.com/u/20646203/HAP.png

HAP Q:
https://dl.dropboxusercontent.com/u/20646203/HAPQ.png

Differences are subtle... best if you put on layers in Photoshop or something like that so you can toggle on/off to see differences.  Here is what I see:
HAP:
- overall color/contrast looks very very close to original
- in upper left corner I see some color banding.  slight, but there.

HAP Q:
- overall color/contrast is off a bit from the original.  Less contrast and a bit less saturation I  would say
- upper left corner banding is noticeably worse, and I would say unacceptable for my application.

So... What's my question?  Well - if these results were opposite, I think it would make a lot of sense, and I would just assume the larger file/better setting is getting better results.. but the fact that HAP Q looks worse than HAP has me asking... Why?  And can I better understand what kind of content HAP is 'good' at and 'not so good' at?

Thanks for listening :-)
-kt

**Comment by tromerk** [comment] 2016-02-11 18:56
Any thoughts on this?  Am I imagining it?

**Comment by Qlex42** [comment] 2017-01-19 18:52
Hap and HapAlpha use straight forward RGB color space, so no big deal except for the DXT compression.
Color banding is probably due to the YCoCg color space transformation only done in HapQ.
The mandatory 8 bits quantization in YCoCg may be more destructive than in RGB for specifics color ranges.
Maybe the quicktime hap encoder shader and the decoding shader of the playing software do not match perfectly.

Here my implementation, not sure it's perfect...

    vec4 coCgSY =...
    coCgSY += vec4(-0.5 * 256.0 / 255.0, -0.5 * 256.0 / 255.0, 0.0, 0.0);
    float scale = ( coCgSY.z * ( 255.0 / 8.0 ) ) + 1.0;
    float co = coCgSY.x / scale;
    float cg = coCgSY.y / scale;
    float y = coCgSY.w;
    return vec4(y + co - cg, y + cg, y - co - cg, 1.0);

**Comment by bangnoise** [comment] 2017-01-19 19:22
Sorry, not sure why this never got a reply. This is a duplicate of #16 

Your original files are no longer available, but perhaps they had areas of gradient - gradients are definitely Hap and Hap Q's weakness.

**Closed by bangnoise** 2017-01-19 19:22 UTC
