### ISSUE TITLE
Slow Rendering to HAP

### ISSUE THREAD

**Issue by kolakolakola** [Vidvox/hap-qt-codec#21] opened 2015-09-14 02:16 UTC
I'm finding renders to HAP out of AE CC are going really slow.
A 10 second test file at 1280x720 with white noise is taking 3m43s to render to HAP.
Rendering to HAP-Q, DXV, ProRes, Animation, or a TGA sequence takes between 10-15s.

Is this normal?
I am using Mac OS X, and have tested on two machines w/ HAP codec v4, v5, and v6.

**Comment by bangnoise** [comment] 2015-09-14 11:17
Hap at high quality will take longer to render than Hap Q, but it shouldn't take that much longer. Can you share the simplest possible AE project which illustrates your issue and details of your system (hardware and OS version)?

**Comment by kolakolakola** [comment] 2015-09-14 17:10
This morning I tried Hap (quality=80) vs Hap Q (quality=100) and got render times of 1m48s vs 11s.
Simple AE test project can be found here: http://tempsend.com/4B7661D8B6

![720 rendertimes](https://cloud.githubusercontent.com/assets/14266961/9856203/24e689c0-5ac8-11e5-904f-d3ba1cdb41c9.png)

![system specs](https://cloud.githubusercontent.com/assets/14266961/9856204/2504e384-5ac8-11e5-890d-be4c575df3be.png)

**Comment by bangnoise** [comment] 2015-09-14 19:18
Looks like "normal" render times - the Hap encoder is slow at high quality. If you drop quality below high then a much faster encoder will be used. I'll leave this issue open as we could really do with a faster high quality encoder...

**Comment by jossgray** [comment] 2015-11-05 12:51
Is it the DXT encoder that takes time?

**Comment by bangnoise** [comment] 2015-11-05 13:56
@jossgray yep

**Comment by 780alpha** [comment] 2016-05-19 19:08
I'm going to piggyback on this slow render thread.  I have been having an issue with rendering to HAP 100% at a resolution of 5400 x 1850.  The render times were unworkable and I couldn't figure out why this particular resolution was giving me such issues.  Trying to render out a 3 min clip took hours and I had a whole 1.5 hour show to encode.  What I discovered was that simply changing the resolution to 5400 x 1855 solved the problem.  Watching my system monitor, I could see that when I was rendering at 5400 x 1850, only half the cores were being utilized at less than 40%.  But when I would render at 5400 x 1855, all cores were being utilized at near 100%.  The resulting render times where 5x faster with the slightly higher resolution.  I was able to replicate this behavior across Mac and Windows platforms as well as between different encoding software and different source files.  Any thoughts on why this might be happening?

**Comment by bangnoise** [comment] 2016-05-20 11:54
@780alpha thanks for the details. There does appear to be an issue which causes too few cores to be utilised for some frame dimensions.

**Comment by bangnoise** [comment] 2016-05-20 17:36
@780alpha (and anyone else who might have hit the same issue) - I've just put up version 11 with a fix for this. It would be helpful if you could confirm you no longer see a penalty for 5400 x 1850 frames.

**Comment by 780alpha** [comment] 2016-05-20 18:12
I can confirm that this update resolved the issue I was having.  Thank you!

**Closed** 2019-03-04 20:43 UTC
